### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by githublister** [nomiclabs/hardhat-hackathon-boilerplate#99]
invalid address or ENS name (argument="name", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.7.0)
    at Logger.makeError (http://localhost:3000/static/js/bundle.js:8012:19)
    at Logger.throwError (http://localhost:3000/static/js/bundle.js:8021:16)
    at Logger.throwArgumentError (http://localhost:3000/static/js/bundle.js:8024:17)
    at http://localhost:3000/static/js/bundle.js:5637:14
    at Generator.next (<anonymous>)
    at fulfilled (http://localhost:3000/static/js/bundle.js:5585:24)

**Comment by githublister** [comment]
![image](https://github.com/NomicFoundation/hardhat-boilerplate/assets/20219606/e0db52f7-5849-410a-b6d9-8481a6091f20)

**Comment by fvictorio** [comment]
You are passing undefined to some method.

This repo is not meant to be used for support, sorry.
